# This configuration will cause altimeter to scan the currently logged in account
# and any of its subaccounts, using the OrganizationAccountAccessRole

artifact_path = "/tmp/altimeter_multi_account"
graph_name = "alti"
pruner_max_age_min = 4320 # prune graphs over 3 days old

[accessor]
    cache_creds = true
    [[accessor.multi_hop_accessors]]
        role_session_name = "altimeter"
        [[accessor.multi_hop_accessors.access_steps]]
            role_name = "OrganizationAccountAccessRole"

[scan]
    # accounts to scan
    accounts = []
    # regions to scan. If empty, scan all available regions
    regions = []
    # if true, discover and scan subaccounts of the above accounts
    scan_sub_accounts = true
    # preferred regions to use when scanning non-regional resources (e.g. IAM policies)
    preferred_account_scan_regions = [
        "us-west-1",
        "us-west-2",
        "us-east-1",
        "us-east-2",
    ]

[concurrency]
    # The following settings control scan concurrency.
    #
    # In general, the maximum number of concurrent scan operations is
    #   max_account_scan_threads * max_svc_scan_threads
    max_account_scan_threads = 16           # number of account scan threads to spawn
    max_svc_scan_threads = 64               # the number of scan threads to spawn in each account scan thread
